<h1 align="center" style="font-size:3em;">1906354 TnT SESSIONAL</h1>

In [1]:
import numpy as np
import pandas as pd

## Q1 A magic square is a matrix all of whose row sums, column sums, and the sums of the two diagonals are the same. (One diagonal of a matrix goes from the top left to the bottom right, and the other diagonal goes from top right to bottom left.) Show by direct computation that if the matrix A is given by
A=np.array([[17, 24, 1, 8, 15],  
[23, 5, 7, 14, 16],
                      [
[4, 6, 13, 20, 22],                    
[10, 12, 19, 21, 3],
                     
[11, 18, 25, 2, 9]])

The matrix A has 5-row sums (one for each row), 5 column sums (one for
each column), and two diagonal sums. These 12 sums should all be exactly the
same, and you could verify that they are the same by printing them and “seeing”
that they are the same. It is easy to miss small differences among so many
numbers, though. Instead, verify that A is a magic square by constructing the 5
column sums and computing the maximum and minimum values of the column sums. Do
the same for the 5-row sums, and compute the two diagonal sums. Check that
these six values are the same. If the maximum and minimum values are the same,
the flyswatter principle says that all values are the same.






Hints: The function np.diag extracts the diagonal of a matrix, and the
function np.fliplr extracts the other diagonal.

In [2]:
def isMagicSquare(arr):
    n = len(arr)
    sumd1 = 0
    sumd2 = 0
    for i in range(n):
        sumd1 += arr[i][i]
        sumd2 += arr[i][n-i-1]
    if not(sumd1 == sumd2):
        return False
    for i in range(n):
        sumr = 0
        sumc = 0
        for j in range(n):
            sumr += arr[i][j]
            sumc += arr[j][i]
        if not(sumr == sumc == sumd1):
            return False
    return True

In [3]:
arr = np.array([[17, 24, 1, 8, 15],
              [23, 5, 7, 14, 16],
              [4, 6, 13, 20, 22],
              [10, 12, 19, 21, 3],
              [11, 18, 25, 2, 9]])

arr

array([[17, 24,  1,  8, 15],
       [23,  5,  7, 14, 16],
       [ 4,  6, 13, 20, 22],
       [10, 12, 19, 21,  3],
       [11, 18, 25,  2,  9]])

In [4]:
if (isMagicSquare(arr)) :
    print( "It is a Magic Square.")
else :
    print( "It is not a magic Square.")

It is a Magic Square.


In [5]:
rowSum = np.sum(arr, axis=1)
rowSum

array([65, 65, 65, 65, 65])

In [6]:
colSum = np.sum(arr, axis=0)
colSum

array([65, 65, 65, 65, 65])

In [7]:
diagonal1 = sum(np.diagonal(arr))
diagonal1

65

In [8]:
diagonal2 = sum(np.fliplr(arr).diagonal())
diagonal2

65

In [9]:
for i in rowSum:
    result = np.all(rowSum == rowSum[0])
    if result:
        print('Equal.')
    else:
        print('Equal.')

Equal.
Equal.
Equal.
Equal.
Equal.


In [10]:
for i in rowSum:
    result = np.all(colSum == colSum[0])
    if result:
        print('Equal.')
    else:
        print('Equal.')

Equal.
Equal.
Equal.
Equal.
Equal.


## Q2 WAP TO PERFORM RIGHT JOIN AND INNER JOIN USING PANDAS.

In [11]:
data1 = pd.DataFrame({'id': [2, 12, 20, 22], 'val1': ['a', 'b', 'c', 'd']})
data1

id val1
0   2    a
1  12    b
2  20    c
3  22    d

In [12]:
data2 = pd.DataFrame({'id': [4, 5, 8, 12], 'val1': ['p', 'q', 'r', 's']})
data2

id val1
0   4    p
1   5    q
2   8    r
3  12    s

In [13]:
right = pd.merge(data1, data2, on='id', how='right')
right

id val1_x val1_y
0   4    NaN      p
1   5    NaN      q
2   8    NaN      r
3  12      b      s

In [14]:
inner = pd.merge(data1, data2, on='id', how='inner')
inner

id val1_x val1_y
0  12      b      s

<h1 align="center" style="font-size:3em;">1906354 TnT SESSIONAL</h1>