<h1 align="center" style="font-size:50px">1906354 TNT LAB9</h1>

In [1]:
import numpy as np
import pandas as pd
import scipy
from scipy import stats

import warnings
warnings.filterwarnings("ignore")

# 1. Create a 5X4 integer array from a range between 100 to 1999 such that the difference between each element is 21.

In [2]:
sampleArray = np.arange(100, 999, 45)
sampleArray = sampleArray.reshape(5,4)
sampleArray

array([[100, 145, 190, 235],
       [280, 325, 370, 415],
       [460, 505, 550, 595],
       [640, 685, 730, 775],
       [820, 865, 910, 955]])

# 2. WAP to create DataFrame from dict of lists.

In [3]:
data = {'Category':['Array', 'Stack', 'Queue'],
        'Marks':[20, 21, 19]}
df = pd.DataFrame(data)
df

Category  Marks
0    Array     20
1    Stack     21
2    Queue     19

# 3. WAP to slice a range of values from an array.

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


# 4. WAP TO DEMOSNTRATE BASIC ARITHMATIC OPERATIONS ON ARRAY.

In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [6]:
np.add(a,b)

array([ 6,  8, 10, 12])

In [7]:
np.subtract(a,b)

array([-4, -4, -4, -4])

In [8]:
np.multiply(a,b)

array([ 5, 12, 21, 32])

In [9]:
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

# 5. Take a 5*5 matrix and prints its transpose and diagonal matrix.

In [10]:
a = np.array([[1, 2], [3, 4]])

In [11]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [12]:
a.diagonal()

array([1, 4])

# 6. WAP to find roots of a Quadratic equation using numpy.

In [13]:
coeff = [1,3,-4]
np.roots(coeff)

array([-4.,  1.])

# 7. WAP to create a dict with series. Create a dataframe and return the first row and the last row.

In [14]:
data = {'Category':['Array', 'Stack', 'Queue'],
        'Marks':[20, 21, 19]}
df = pd.DataFrame(data)

In [15]:
df

Category  Marks
0    Array     20
1    Stack     21
2    Queue     19

In [16]:
df.head(1)

Category  Marks
0    Array     20

In [17]:
df.tail(1)

Category  Marks
2    Queue     19

# 8. WAP TO FIND THE AVERAGE, MODE, STANDARD DEVIATION , VARI ANCE OF ARRAY ELEMENT using scipy.

In [18]:
scipy.mean([1, 3, 27])

10.333333333333334

In [19]:
stats.mode([1, 3, 27])[0][0]

1

In [20]:
stats.tstd([1, 3, 27])

14.468356276140469

In [21]:
stats.variation([1, 3, 27], ddof=1)

1.400163510594239

# 9. WAP TO PERFORM RIGHT JOIN AND INNER JOIN using pandas.

In [22]:
temp = {'id': [1, 2, 10, 12], 'val1': ['a', 'b', 'c', 'd']}
df1 = pd.DataFrame(temp)
temp = {'id': [1, 2, 9, 8], 'val1': ['p', 'q', 'r', 's']}
df2 = pd.DataFrame(temp)

In [23]:
df_inner = pd.merge(df1, df2, on='id', how='inner')
df_inner

id val1_x val1_y
0   1      a      p
1   2      b      q

In [24]:
df_right = pd.merge(df1, df2, on='id', how='right')
df_right

id val1_x val1_y
0   1      a      p
1   2      b      q
2   9    NaN      r
3   8    NaN      s

# 10. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

In [25]:
data_type = [('name', 'S30'), ('height', float), ('class', int)]
students_details = [('XYZ', 51.2, 4), ('ABC', 64.3, 5),('DEF', 45.7, 2), ('IJK', 67.3, 11)]
students = np.array(students_details, dtype=data_type)

In [26]:
students

array([(b'XYZ', 51.2,  4), (b'ABC', 64.3,  5), (b'DEF', 45.7,  2),
       (b'IJK', 67.3, 11)],
      dtype=[('name', 'S30'), ('height', '<f8'), ('class', '<i4')])

In [27]:
students = np.sort(students, order='height')
students

array([(b'DEF', 45.7,  2), (b'XYZ', 51.2,  4), (b'ABC', 64.3,  5),
       (b'IJK', 67.3, 11)],
      dtype=[('name', 'S30'), ('height', '<f8'), ('class', '<i4')])

# 11. WAP to find profit or loss for a given CP and SP.

In [28]:
cp=float(input("Enter the Cost Price : "));
sp=float(input("Enter the Selling Price : "));
if cp==sp:
    print("No Profit No Loss")
else:
    if sp>cp:
        print("Profit of ",sp-cp)
    else:
        print("Loss of ",cp-sp)

Enter the Cost Price : 100.5
Enter the Selling Price : 129.79
Profit of  29.289999999999992


# 12.WAP to create a dict with series. Create a dataframe and return the first row and the last row.

In [29]:
data = {'Category':['Array', 'Stack', 'Queue'],
        'Marks':[20, 21, 19]}
df = pd.DataFrame(data)

In [30]:
df

Category  Marks
0    Array     20
1    Stack     21
2    Queue     19

In [31]:
df.head(1)

Category  Marks
0    Array     20

In [32]:
df.tail(1)

Category  Marks
2    Queue     19

# 13. TAKE AN ARRAY WITH ATLEAT 7 INTEGET VALUES AND CALCULATE THEIR RECIPROCAL AND FACTORIAL.

In [33]:
arr = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0])
reciprocal = [np.reciprocal(x) for x in arr]
factorial = [np.math.factorial(x) for x in arr]

In [34]:
reciprocal

[1.0,
 0.5,
 0.3333333333333333,
 0.25,
 0.2,
 0.16666666666666666,
 0.14285714285714285]

In [35]:
factorial

[1, 2, 6, 24, 120, 720, 5040]

# 14 WAP to iterate rows using itertuples.

In [36]:
df = pd.DataFrame({'num_legs': [4, 2], 'num_wings': [0, 2]}, index=['dog', 'hawk'])
rows = [row for row in df.itertuples()]
rows

[Pandas(Index='dog', num_legs=4, num_wings=0),
 Pandas(Index='hawk', num_legs=2, num_wings=2)]